### ISSUE TITLE
Add a save option [Feature]

### ISSUE THREAD

**Issue by jeanpaulh** [xitanggg/open-resume#79] opened 2023-10-31 21:49 UTC
I have to say thanks; it is looking great.
I shared an issue about the PDF file that you generated isn't being passed correctly when you import it.
Being a PDF, I would think this would be hard; maybe a better option is to add a save option [MetaData]!!!!

keep up the good work.

JP

**Comment by tracker1** [comment] 2024-01-03 15:20
Dupe of #62

**Comment by jeanpaulh** [comment] 2024-02-13 14:20
dupe

**Closed** 2024-02-13 14:20 UTC
